name: dask_env
channels:
  - conda-forge
dependencies:
  # Basic Python stuff
  - python=3.8
  - pip
  # Jupyter notebook stuff
  - nodejs
  - notebook
  - nbstripout
  - jupyterlab[version='>=2.0.0']
  - rise
  # Dask stuff
  - dask=2.20.0
  - dask-core
  - dask-ml
  - dask-glm
  - distributed=2.20.0
  # For visualization
  - matplotlib
  - python-graphviz
  - bokeh[version='>=2.0.0']
  - dask-labextension[version='>=2.0.0']
  # Standard data science stuff
  - numpy[version='>=1.18.1']
  - scikit-learn[version='>=0.22.1']
  - pandas[version='>=1.0.1']
  - h5py
